export const LOAD_SCHEDULE = 'LOAD_SCHEDULE';
export const CHANGE_SCHEDULE_TABLE = 'CHANGE_SCHEDULE_TABLE';
export const MARK_ALL_DAY = 'MARK_ALL_DAY';
export const UNMARK_ALL_DAY = 'UNMARK_ALL_DAY';
export const TRANSFORM_DATA = 'TRANSFORM_DATA';
